In [1]:
import polars as pl

In [2]:
df = pl.read_csv("hardpoints_template.csv")
df

shape: (40, 5)
┌────────┬───────────────┬─────────┬────────┬───────┐
│ corner ┆ point         ┆ x_mm    ┆ y_mm   ┆ z_mm  │
│ ---    ┆ ---           ┆ ---     ┆ ---    ┆ ---   │
│ str    ┆ str           ┆ f64     ┆ f64    ┆ f64   │
╞════════╪═══════════════╪═════════╪════════╪═══════╡
│ FL     ┆ UCA_IN_FRONT  ┆ 60.0    ┆ 150.0  ┆ 295.0 │
│ FL     ┆ UCA_IN_REAR   ┆ -70.0   ┆ 150.0  ┆ 295.0 │
│ FL     ┆ UCA_OUT       ┆ -5.0    ┆ 590.0  ┆ 280.0 │
│ FL     ┆ LCA_IN_FRONT  ┆ 90.0    ┆ 130.0  ┆ 162.0 │
│ FL     ┆ LCA_IN_REAR   ┆ -70.0   ┆ 130.0  ┆ 162.0 │
│ …      ┆ …             ┆ …       ┆ …      ┆ …     │
│ RR     ┆ LCA_OUT       ┆ -1535.0 ┆ -600.0 ┆ 152.0 │
│ RR     ┆ TIE_ROD_IN    ┆ -1600.0 ┆ -180.0 ┆ 200.0 │
│ RR     ┆ TIE_ROD_OUT   ┆ -1610.0 ┆ -580.0 ┆ 195.0 │
│ RR     ┆ WHEEL_CENTER  ┆ -1545.0 ┆ -610.0 ┆ 220.0 │
│ RR     ┆ CONTACT_PATCH ┆ -1545.0 ┆ -610.0 ┆ 0.0   │
└────────┴───────────────┴─────────┴────────┴───────┘

In [4]:
df.write_excel("hardpoints_template.xlsx")

In [18]:
import polars as pl
df_new = pl.read_excel("SKELLY V1.xlsx")
df_new = pl.read_csv("SKELLY V1.csv", encoding="utf8-lossy")
df_new

shape: (40, 5)
┌─────┬───────────────┬─────────┬────────┬────────┐
│ FL  ┆ UCA_IN_FRONT  ┆ 115.0   ┆ 225.0  ┆ 292.64 │
│ --- ┆ ---           ┆ ---     ┆ ---    ┆ ---    │
│ str ┆ str           ┆ f64     ┆ f64    ┆ str    │
╞═════╪═══════════════╪═════════╪════════╪════════╡
│ FL  ┆ UCA_IN_REAR   ┆ -115.0  ┆ 225.0  ┆ 292.64 │
│ FL  ┆ UCA_OUT       ┆ -27.48  ┆ 551.49 ┆ 364.92 │
│ FL  ┆ LCA_IN_FRONT  ┆ 150.0   ┆ 225.0  ┆ 106.44 │
│ FL  ┆ LCA_IN_REAR   ┆ -150.0  ┆ 225.0  ┆ 106.44 │
│ FL  ┆ LCA_OUT       ┆ 0.0     ┆ 578.97 ┆ 104.92 │
│ …   ┆ …             ┆ …       ┆ …      ┆ …      │
│ RR  ┆ TIE_ROD_IN    ┆ -1600.0 ┆ -180.0 ┆ 200.0  │
│ RR  ┆ TIE_ROD_OUT   ┆ -1610.0 ┆ -580.0 ┆ 195.0  │
│ RR  ┆ WHEEL_CENTER  ┆ -1545.0 ┆ -610.0 ┆ 220.0  │
│ RR  ┆ CONTACT_PATCH ┆ -1545.0 ┆ -610.0 ┆ 0.0�   │
│ RR  ┆ CONTACT_PATCH ┆ -1545.0 ┆ -610.0 ┆ 0.0    │
└─────┴───────────────┴─────────┴────────┴────────┘

In [17]:
df_new = df_new.write_csv("SKELLY V1.csv")

In [19]:
((12*220*(3.812**2))/2)*0.00002366

0.4538313107328

In [ ]:
(38527*(1.03**2)*math.cos(math.radians(15)) )/1000

39.48057056988377

In [31]:
(266.65/524.47)

0.508418022003165